[[feed]]
id = "cruquiusweg-fun-group"
title = "Cruquiusweg Fun Group"
link = "https://www.meetup.com/cruquiusweg-fun-group/"
description = "Meetup events feed"
ical_url = "https://www.meetup.com/cruquiusweg-fun-group/events/ical/"
